### ISSUE TITLE
License Discussion

### ISSUE THREAD

**Issue by braydentang1** [UBC-MDS/encodeR#74]
As described in final_project.

**Comment by robilizando** [comment]
As a team, we have reviewed and discussed the two most common licenses available from the https://choosealicense.com website for our project. Namely, the "GNU GPLv3" and the "MIT" licenses. 

Although we liked the  GNU GPLv3 feature that allows others to use our code in their software, but conditions that they disclose their source code, we feel that this would limit the possibilities for users and developers to improve and make further contributions to this package. 

The MIT license, on the other hand, is flexible enough to grant permission for commercial and private usage, and modification and distribution of our code or derivatives, but does not impose source code disclosure. Therefore, we concluded that adopting the MIT license was a better choice for our project.

The MIT license provides a good "win-win" compromise: We would receive the necessary public recognition and acknowledgment, and they get to use the code as they wish. This we feel sets the right environment for collaboration and improvements.
